### ISSUE TITLE
Permissions when installed in Python system-level directory

### ISSUE THREAD

**Issue by mfreer** [eufarn7sp/egads#6]
When importing Egads-lineage from a system directory (my site-packages directory where pip installs to on a Mac), Egads is unable to write the log, ini, and other files to the directory specified in the egads_utils.py file. However, if I run python/ipython with elevated privileges, I'm able to successfully import Egads... Is it possible to configure Egads in some way where the default path used for these runtime files is defined by the user?

**Comment by olivierpascalhenry** [comment]
Hi Matt,

I will see what I can do.
As all my Python installations are in my Home and as EGADS is not intended to be installed in a system directory, I didn't think about a solution for this particular case.
I don't have a Mac or a virtual machine running macOS, so I am not sure if my solution will work.

Olivier

**Comment by olivierpascalhenry** [comment]
In an update, I moved the configuration file, the log and the user algorithm structure in the $HOME directory, in a dedicated folder. It should work better now. Let me know !

**Comment by mfreer** [comment]
Thanks I'll give it a shot! In the meantime, I've been running it in a local directory, and as you say, if this is the way it is designed, it shouldn't be a problem for my current use case. 

I'll let you know how it goes once I've had a chance to test it.
